[package]
name = "caesar_cipher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cipher-crypt = "^0.16"
clippy = "0.0.302"
scanrs = "0.3.0"
